CREATE FUNCTION add_new_shop(name VARCHAR(64))
  RETURNS BOOLEAN AS
$$ 
BEGIN
  INSERT INTO shop
  VALUES (DEFAULT, name);
  RETURN TRUE;
  EXCEPTION
    WHEN OTHERS THEN
      RETURN FALSE;
END;
$$ LANGUAGE plpgsql;
